name: "Comfort to MQTT - Dev"
description: "Cytech Comfort to MQTT bridge"
version: "1.1.1"
slug: "comfort2mqtt"
init: false
startup: application
apparmor: true
panel_icon: "mdi:alarm-panel-outline"
codenotary: notary@home-assistant.io
url: https://github.com/djagerif/comfort2mqtt
hassio_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
map:
  - addon_config:ro
options:
  mqtt_broker_address: core-mosquitto
  mqtt_user: null
  mqtt_password: null
  mqtt_broker_port: 1883
  mqtt_protocol: TCP
  mqtt_encryption: false
  broker_ca: "ca.crt"
  require_certificate: false
  broker_client_cert: "client.crt"
  broker_client_key: "client.key"
  comfort_address: null
  comfort_port: 1002
  comfort_login_id: null
  comfort_cclx_file: "comfigurator.cclx"
  log_verbosity: INFO
  alarm_inputs: 8
  alarm_outputs: 0
  alarm_rio_inputs: 0
  alarm_rio_outputs: 0
  alarm_responses: 0
  #auto_discover: false
  comfort_time: false
schema:
  mqtt_broker_address: str
  mqtt_user: str
  mqtt_password: password
  mqtt_broker_port: int(1024,65535)?
  mqtt_protocol: list(TCP|WebSockets)?
  mqtt_encryption: bool?
  broker_ca: str?
  require_certificate: bool?
  broker_client_cert: str?
  broker_client_key: str?
  comfort_address: str
  comfort_port: int?
  comfort_login_id: password
  comfort_cclx_file: str?
  log_verbosity: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
  alarm_inputs: list(8|16|24|32|40|48|56|64|72|80|88|96|104|112|120|128)?
  alarm_outputs: list(0|8|16|24|32|40|48|56|64|72|80|88|96|104|112|120|128)?
  alarm_rio_inputs: int(0,120)?
  alarm_rio_outputs: int(0,120)?
  alarm_responses: int(0,1024)?
  #auto_discover: bool?
  comfort_time: bool?
#image: "ghcr.io/djagerif/{arch}-addon-comfort2mqtt"  #  For future docker image release !!!
