name: "Comfort to MQTT"
description: "Cytech Comfort II Ultra to MQTT bridge"
version: "1.0.3"
slug: "comfort2mqtt"
init: false
startup: application
apparmor: true
panel_icon: "mdi:alarm-panel-outline"
codenotary: notary@home-assistant.io
url: https://github.com/djagerif/comfort2mqtt
hassio_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mqtt:need
map:
  - addon_config:ro
options:
  mqtt_broker_address: core-mosquitto
  mqtt_user: null
  mqtt_password: null
  mqtt_broker_port: 1883
  mqtt_protocol: TCP
  #mqtt_encryption: false     # For future development !!!
  comfort_address: null
  comfort_port: 1002
  comfort_login_id: null
  log_verbosity: INFO
  alarm_inputs: 8
  alarm_outputs: 0
  alarm_rio_inputs: 0
  alarm_rio_outputs: 0
  alarm_responses: 0
  comfort_time: false
schema:
  mqtt_broker_address: str
  mqtt_user: str
  mqtt_password: password
  mqtt_broker_port: int(1024,65535)?
  mqtt_protocol: list(TCP|WebSockets)?
  #mqtt_encryption: bool?     #  For future development !!!
  comfort_address: str
  comfort_port: int?
  comfort_login_id: password
  log_verbosity: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)?
  alarm_inputs: int(8,128)?
  alarm_outputs: int(0,128)?
  alarm_rio_inputs: int(0,120)?
  alarm_rio_outputs: int(0,120)?
  alarm_responses: int(0,1024)?
  #broker_ca: str?            #  For future development !!!
  #broker_client_cert: str?   #  For future development !!!
  #broker_client_key: str?    # For future development !!!
  comfort_time: bool
#image: "ghcr.io/djagerif/{arch}-addon-comfort2mqtt"  #  For future docker image release !!!
  
